Update patch set 3
Patch Set 3:

> Patch Set 3: Verified-1
> 
> When trying to build this change using the CI, to test the job implemented in the same topic, the following error came up:
> 
>   ERROR: /home/jenkins/workspace/plugin-rename-project-bazel-master/plugins/rename-project/BUILD:9:1: Building plugins/rename-project/librename-project__plugin-class.jar (19 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1)
> plugins/rename-project/src/main/java/com/googlesource/gerrit/plugins/renameproject/conditions/RenamePreconditions.java:94: error: incompatible types: Response<List<ProjectInfo>> cannot be converted to List<ProjectInfo>
>       List<ProjectInfo> children = listChildProjectsProvider.get().apply(rsrc);

This is probably because [1] has been submitted in the meantime and broke the build again.

[1] https://gerrit-review.googlesource.com/c/gerrit/+/231719

Patch-set: 3
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>